inputs:
  user:
    description: Username for the user
    default: ""
  email:
    description: Email for the user
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Building the project"
      run: make all
      shell: bash
    - name: "Executing project"
      run: make runargs id="1" user=${{ inputs.user }} email=${{ inputs.email }}
      shell: bash
    - name: "Cleaning up the project"
      run: make clean
      shell: bash