name: Sample Actions Demo
run-name: Building project by ${{ github.actor }}
on: [push]
jobs:
  Run-with-default-args:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "List out files"
        run: ls
      - name: build-userproject
        uses: .github/actions/userproject
        id: userproject
        with:
          user: "Tanay Mishra"
          email: "tanay.mishra@schrodinger.com"
      - name: "List out files"
        run: ls