name: Sample Actions Demo
run-name: Building project by ${{ github.actor }} using predefined action
on: [push]
jobs:
  Run-with-params:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build-userproject
        uses: ./.github/actions/userproject
        id: userproject
        with:
          user: "Tanay Mishra"
          email: "tanay.mishra@schrodinger.com"