name: Sample Actions Demo
run-name: Building project by ${{ github.actor }}
on: [push]
jobs:
  Run-with-default-args:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Checking environment variable"
      - name: Building the project
        run: |
          make all
      - name: echo "Executing project"
        run: "make run && make clean"
      - name: "Setting the environment variable"
        run: echo "USER=mishra" >> "$GITHUB_ENV" 
      - name: "Running the project again"
        run: "make run"
      - name: "Cleaning up the project"
        run: "make clean"
      - run: echo "This job's status is ${{ job.status }}."